### ISSUE TITLE
CPM numbers

### ISSUE THREAD

**Issue by sruPL** [MarioJim/critical_path_calc#1]
Hey, could you explain what do the 4 numbers mean in each section of CPM? I checked readme, but couldn't find answer to that. So my task is to 

- Determine the earliest possible time of the event
- Determine the latest possible time of the event occurrence
- Determine the critical path

I can see the critical path but I'm unsure about the other 2 and if your calc involves these factors, thanks in advance for the answer.

**Comment by MarioJim** [comment]
Yeah, no problem. The top row of numbers are for the earliest possible case, left and right being the start time and the end time respectively. The bottom row of numbers are the latest possible case, left and right also being start and end time.

If the node has a blue color it means it is either the start or the end of the critical path, and every node with a red fill is also part of the critical path. Finally, green nodes have different times for their earliest and latest cases, meaning they aren't part of the critical path.
